name: Testes automatizados

on:
  push:
    branches:
      - master
      - dev

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
  
      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Criar arquivo .env
        run: |
          echo "PORT=5001" >> .env
          echo "URI=${{ secrets.MONGO_DB_URI }}" >> .env
 
      - name: Instalar dependências Node.js
        run: npm install

      - name: Rodar projeto
        run: nohup npm run dev > /dev/null 2>&1 &

      - name: Aguardar 10 segundos
        run: sleep 10s

      - name: Executar pytest
        run: pytest .\tests\